# Generated by Django 4.0.5 on 2022-06-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
